// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChecknotifController from "./checknotif_controller"
application.register("checknotif", ChecknotifController)

import DisplayCardInfosController from "./display_card_infos_controller"
application.register("display-card-infos", DisplayCardInfosController)

import EditController from "./edit_controller"
application.register("edit", EditController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HideController from "./hide_controller"
application.register("hide", HideController)

import InsertController from "./insert_controller"
application.register("insert", InsertController)

import QuoteController from "./quote_controller"
application.register("quote", QuoteController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import SpinWheelController from "./spin_wheel_controller"
application.register("spin-wheel", SpinWheelController)
