// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DisplayCardInfosController from "./display_card_infos_controller"
application.register("display-card-infos", DisplayCardInfosController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
