meta_product_name: "Spe@kitOut"
meta_title: "Spe@kitOut - will make you feel better"
meta_description: "Feeling down? Speak it out at Spe@kitOut will make you feel better!"
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
